### PR TITLE
Rebase/0.47.0

### PR DESCRIPTION
**Pull request by aleontiev**

### CODE REVIEW

**Comment by suavesav** [comment]
Review based on https://github.com/pennersr/django-allauth/compare/0.47.0...AltSchool:rebase/0.47.0

Curious about the conflicts in this PR, and the changes in test_settings.py on the diff linked above. But other than that, looks pretty good.

Also were you able to get the tests we added to run/pass? lmk if I can help with QA!

**Comment by aleontiev** [comment]
@suavesav after QAing proxy login and fixing tests, I have squashed all of our commits into one and pushed that here

**Review by suavesav — APPROVED** [review]
QA'd on your feature stack for google and microsoft auth. Might be worth trying this out on automata too in case upstream changes had any effect on behavior there.

**Comment by suavesav** [comment]
now using AltSchool/django-allauth-with-fake

**Pull request closed without merging**
